name: Generate Pacman Contribution Graph
permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:       # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: 'kanchan-sati'

      - name: Move generated files to output folder
        run: |
          mkdir -p output
          cp -v dist/* output/

      - name: Commit and push generated files to main
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Update Pacman contribution graph"
          add: "output/*"
          push: true
